// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fin_uslugi/features/banks/data/models/bank_model.dart';
import 'package:fin_uslugi/features/banks/data/models/products_info.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/credit_card_response.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/credit_response.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/debit_card_response.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/product.dart';
import 'package:fin_uslugi/features/cards/data/models/investment/investment_response.dart';
import 'package:fin_uslugi/features/cards/data/models/mortgages/mortgage_response.dart';
import 'package:fin_uslugi/features/coupons/data/models/coupon_item_model.dart';
import 'package:fin_uslugi/features/coupons/data/models/coupon_model.dart';
import 'package:fin_uslugi/features/coupons/data/models/features_model.dart';
import 'package:fin_uslugi/features/coupons/data/models/meta_model.dart';
import 'package:fin_uslugi/features/coupons/data/models/retailer_model.dart';
import 'package:fin_uslugi/features/coupons/presentation/pages/favourites/data/models/coupon_favourite_model.dart';
import 'package:fin_uslugi/features/loans/data/models/credit/loan_main_model.dart';
import 'package:fin_uslugi/features/programms/data/models/article_categories.dart';
import 'package:fin_uslugi/features/programms/data/models/article_category.dart';
import 'package:fin_uslugi/features/programms/data/models/article_data_model.dart';
import 'package:fin_uslugi/features/programms/data/models/article_model.dart';
import 'package:fin_uslugi/features/programms/data/models/content_block_model.dart';
import 'package:fin_uslugi/features/programms/data/models/params_model.dart';
import 'package:fin_uslugi/features/programms/data/models/product_item_model.dart';
import 'package:fin_uslugi/features/programms/data/models/product_model.dart';
import 'package:fin_uslugi/features/programms/data/models/product_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AdditionalInfoAdapter());
    registerAdapter(AppAdapter());
    registerAdapter(ArticleAdapter());
    registerAdapter(ArticleCategoriesAdapter());
    registerAdapter(ArticleCategoryAdapter());
    registerAdapter(ArticleDataAdapter());
    registerAdapter(BankInfoAdapter());
    registerAdapter(BankingCategoryAdapter());
    registerAdapter(ContentBlockAdapter());
    registerAdapter(CouponFavouriteModelAdapter());
    registerAdapter(CouponItemAdapter());
    registerAdapter(CouponModelAdapter());
    registerAdapter(CreditCardResponseAdapter());
    registerAdapter(CreditResponseAdapter());
    registerAdapter(DebitCardResponseAdapter());
    registerAdapter(EmailAdapter());
    registerAdapter(FAQAdapter());
    registerAdapter(FeaturesModelAdapter());
    registerAdapter(InvestmentResponseAdapter());
    registerAdapter(LoanMainModelAdapter());
    registerAdapter(MetaAdapter());
    registerAdapter(MetaModelAdapter());
    registerAdapter(MortgageResponseAdapter());
    registerAdapter(ParamsModelAdapter());
    registerAdapter(PhoneAdapter());
    registerAdapter(ProductItemModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductTypeAdapter());
    registerAdapter(ProductsInfoAdapter());
    registerAdapter(RetailerModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AdditionalInfoAdapter());
    registerAdapter(AppAdapter());
    registerAdapter(ArticleAdapter());
    registerAdapter(ArticleCategoriesAdapter());
    registerAdapter(ArticleCategoryAdapter());
    registerAdapter(ArticleDataAdapter());
    registerAdapter(BankInfoAdapter());
    registerAdapter(BankingCategoryAdapter());
    registerAdapter(ContentBlockAdapter());
    registerAdapter(CouponFavouriteModelAdapter());
    registerAdapter(CouponItemAdapter());
    registerAdapter(CouponModelAdapter());
    registerAdapter(CreditCardResponseAdapter());
    registerAdapter(CreditResponseAdapter());
    registerAdapter(DebitCardResponseAdapter());
    registerAdapter(EmailAdapter());
    registerAdapter(FAQAdapter());
    registerAdapter(FeaturesModelAdapter());
    registerAdapter(InvestmentResponseAdapter());
    registerAdapter(LoanMainModelAdapter());
    registerAdapter(MetaAdapter());
    registerAdapter(MetaModelAdapter());
    registerAdapter(MortgageResponseAdapter());
    registerAdapter(ParamsModelAdapter());
    registerAdapter(PhoneAdapter());
    registerAdapter(ProductItemModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductTypeAdapter());
    registerAdapter(ProductsInfoAdapter());
    registerAdapter(RetailerModelAdapter());
  }
}
