// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/credit_card_response.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/credit_response.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/debit_card_response.dart';
import 'package:fin_uslugi/features/cards/data/models/credit/search_responses/product.dart';
import 'package:fin_uslugi/features/cards/data/models/investment/investment_response.dart';
import 'package:fin_uslugi/features/cards/data/models/mortgages/mortgage_response.dart';
import 'package:fin_uslugi/features/programms/data/models/article_categories.dart';
import 'package:fin_uslugi/features/programms/data/models/article_category.dart';
import 'package:fin_uslugi/features/programms/data/models/article_data_model.dart';
import 'package:fin_uslugi/features/programms/data/models/article_model.dart';
import 'package:fin_uslugi/features/programms/data/models/content_block_model.dart';
import 'package:fin_uslugi/features/programms/data/models/params_model.dart';
import 'package:fin_uslugi/features/programms/data/models/product_item_model.dart';
import 'package:fin_uslugi/features/programms/data/models/product_model.dart';
import 'package:fin_uslugi/features/programms/data/models/product_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ArticleAdapter());
    registerAdapter(ArticleCategoriesAdapter());
    registerAdapter(ArticleCategoryAdapter());
    registerAdapter(ArticleDataAdapter());
    registerAdapter(BankingCategoryAdapter());
    registerAdapter(ContentBlockAdapter());
    registerAdapter(CreditCardResponseAdapter());
    registerAdapter(CreditResponseAdapter());
    registerAdapter(DebitCardResponseAdapter());
    registerAdapter(InvestmentResponseAdapter());
    registerAdapter(MortgageResponseAdapter());
    registerAdapter(ParamsModelAdapter());
    registerAdapter(ProductItemModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ArticleAdapter());
    registerAdapter(ArticleCategoriesAdapter());
    registerAdapter(ArticleCategoryAdapter());
    registerAdapter(ArticleDataAdapter());
    registerAdapter(BankingCategoryAdapter());
    registerAdapter(ContentBlockAdapter());
    registerAdapter(CreditCardResponseAdapter());
    registerAdapter(CreditResponseAdapter());
    registerAdapter(DebitCardResponseAdapter());
    registerAdapter(InvestmentResponseAdapter());
    registerAdapter(MortgageResponseAdapter());
    registerAdapter(ParamsModelAdapter());
    registerAdapter(ProductItemModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductTypeAdapter());
  }
}
